### ISSUE TITLE
Don't use `#!/usr/bin/env perl` in bin/ysh

### ISSUE THREAD

**Issue by eserte** [ingydotnet/yaml-shell-pm#1]
Problem is --- `ExtUtils::MakeMaker` doesn't convert the shebang if it does not look like `#!perl` or `#!/usr/bin/perl`.

**Comment by ingydotnet** [comment]
Fixed in YAML-Shell-0.69 (by Zilla-Dist-0.0.192)

**Comment by eserte** [comment]
Thanks.
